### ISSUE TITLE
Create in-memory store implementations

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/libsignal-protocol-rs#24]
This is something the Java library does. Having an in-memory store is super useful for testing and exploring the crate. It also serves as an example for implementing the various store types and the expected behaviour.

---

- [ ] `IdentityKeyStore` -> `InMemoryIdentityKeyStore` (see #00).
- [ ]  `PreKeyStore` -> `InMemoryPreKeyStore` (see #00).
- [ ] `SessionStore` -> `InMemorySessionStore` (see #00).
- [ ] `SignedPreKeyStore` -> `InMemorySignedPreKeyStore` (see #00).

**Comment by Michael-F-Bryan** [comment]
Ugh, I can't remove the "bug" tag using GitHub's mobile UI...

**Comment by shekohex** [comment]
I was going to open that issue 😂, actually i think i would take that too :+1:
